id: P006759
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25086
  title: འདུལ་བ་མདོ་རྩ།
  author: ''
  volumes:
    c4be429a81694d10a40df9f659ddac4d:
      image_group_id: I1KG25088
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
