id: P006759
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:25.695981
source_metadata:
  id: bdr:W1KG25086
  title: འདུལ་བ་མདོ་རྩ།
  author: ''
  volumes:
    c4be429a81694d10a40df9f659ddac4d:
      image_group_id: I1KG25088
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
