id: IB38382F9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:21:44+00:00'
last_modified: '2022-06-08T06:39:38.642573+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25086
  title: འདུལ་བ་མདོ་རྩ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5773':
      image_group_id: I1KG25088
      title: ''
      total_pages: 322
      order: 1
      base_file: 5773.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
